### ISSUE TITLE
Keyword-to-Caption Augmentation

### ISSUE THREAD

**Issue by usuyama** [LAION-AI/CLAP#51]
How do you use T5 for Keyword-to-Caption Augmentation? 

I'm checking Section 3.5, but wondering what are the actual prompts for T5:
<img width="545" alt="Screenshot 2022-11-16 at 12 15 00 AM" src="https://user-images.githubusercontent.com/344133/202125206-15cfe03b-b6a2-417d-b587-9c95fb651aa6.png">

**Comment by RetroCirce** [comment]
Hi, thank you for your question.
You can see some demos of the keyword-to-caption augmentation in the page 9 of the paper (https://arxiv.org/pdf/2211.06687.pdf) or from this online appendix (https://retrocirce.github.io/appendix/)

Generally, we use the tags of the audio track and use it to make a sentence (as keyword-to-caption). The sentence may not 100% correctly consistent to the audio track event, but it somewhat leads to better performance since it enriches the diversity of the language embeddings.
