### ISSUE TITLE
Access dataset issue

### ISSUE THREAD

**Issue by Yogurt928** [LAION-AI/CLAP#74]
May I ask about how to access the dataset while using the given code?
In the main.py, it seems to use the following line to copy dataset from aws service:

f"aws s3 cp s3://s-laion-audio/webdataset_tar/{dataset_name}/{split}/sizes.json ./json_files/{dataset_name}/{split}/sizes.json"

However, I got "Forbidden" error message as following:
->aws s3 cp s3://s-laion-audio/webdataset_tar/Clotho/train/sizes.json ./json_files/Clotho/train/sizes.json
->fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

Is there any specification about how to configure the aws tool to access the data?

Thanks!

**Comment by lukewys** [comment]
Hi, 

Due to copyright reasons, we cannot release the dataset we train this model on. However, we released [LAION-audio-630K](https://github.com/LAION-AI/audio-dataset/tree/main/laion-audio-630k), the data source we used to compose the dataset with link to each audio and their caption. Please refer to [LAION-audio-630K](https://github.com/LAION-AI/audio-dataset/tree/main/laion-audio-630k) for more details. You could download the dataset and train it locally. To train on the local dataset, please change the `--remotedata` in training scripts (see [experiment_scripts](./experiment_scripts) folder) with `--datasetpath <your dir to datasets>`.

**Comment by Yogurt928** [comment]
I see, thanks for your reply!
